version: '3.4'
services:
  nginx:
    build:
      context : ./nginx/
      dockerfile: Nginx.Dockerfile
    depends_on:
      - api
    ports:
      - "5100:5100"
    restart: always
  api:
    build: .
    environment:
      NODE_ENV: production
      DB_CONNECTION_STRING: mongodb://dta:8npqgJ1Pqo1PlO5ZYDeS8GARIP0gMkvgEKCNT2SrmhyzIv1jNJghm7glfbscMyivGnKXltGijeJMkX5Jg2qajQ==@dta.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@dta@
      DB_CONNECTION_TYPE: CONNECTION_STRING
      DB_NAME: dta
      SECRET_KEY: d0946e53d85e7a611ba84f813b7c8ee7269d1c2cbf5dec78a1d3636c25851865d5eed5b99d96fefe6da6f456c281f52ba11040cf921bdd1a281f94a9973bda77
      DEBUG: True
      LOG: True
      HARD_CODE_USER: True
    restart: always
  
  